lsi: false
safe: true
source: .
title: Sattwik Kumar Sahu
theme: minimal-mistakes-jekyll
baseurl: ""
url: "https://github.com/sattwik-sahu/sattwik-sahu.github.io"
repository: "sattwik-sahu/sattwik-sahu.github.io"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

minimal_mistakes_skin: "default"   # try: "air", "contrast", "dark"

author:
  name   : "Sattwik Kumar Sahu"
  avatar : "/assets/img/sattwik.jpg"
  bio    : "MS Student, IISER Bhopal"
  location : "Bhopal, India"
  email  : "sattwik21@iiserb.ac.in"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sattwik-sahu"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sattwik-kumar-sahu-19b685268"

    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=nMh7tO8AAAAJ"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/radwikc"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sattwik-sahu"
